### ISSUE TITLE
Question: Can we create a postionCloseOrder through RestApi?

### ISSUE THREAD

**Issue by shiqimei** [gateio/gateapi-js#2]
Or can we set a normal order as a [postion.closeOrder](https://github.com/gateio/gateapi-js/blob/master/docs/PositionCloseOrder.md) manually?

**Comment by revilwang** [comment]
Set `close` to true, `size` to 0 in [FuturesOrder](https://github.com/gateio/gateapi-js/blob/master/docs/FuturesOrder.md) to close a position

**Comment by shiqimei** [comment]
Thanks!
