### ISSUE TITLE
Position's definition is outdated

### ISSUE THREAD

**Issue by shiqimei** [gateio/gateapi-js#3]
https://github.com/gateio/gateapi-js/blob/master/docs/Position.md#gateapiposition

The above documentation clarifies keys namings of a `position` object are using `smallCamelCase` style but the fact is that they are following the `snake_case` style. For instance, the mark price's key name is `mark_price` instead of `markPrice`.

**Comment by shiqimei** [comment]
It seems that this error is also applicable to other objects, like `FuturesTicker` etc.

**Comment by revilwang** [comment]
Yes, you're right. I'll dive into the what causes the inconsistency between docs and implementations

**Comment by revilwang** [comment]
The inconsistency has been resolved, by changing the name in docs to snake_case for compatibility concern
