### ISSUE TITLE
Question: What's the relationship between `size` and the amount of BTC? 

### ISSUE THREAD

**Issue by shiqimei** [gateio/gateapi-js#4]
For `BTC/USDT Perpetual`, take `long trade` as an example, the PNL I expected before should be like:

```
(final_price - entry_price) * abs(size)
```

After a bunch of practice/tests, I realized that the real PNL formula should be the following one:

```
(finial_price - entry_price) * abs(size) * 0.0001
```

Here, I got a coefficient `0.0001`, which is actually the amount the BTC I bought. So my question is `size: 1` meaning `0.0001 BTC`, is this a determined proportional relationship? Why this extra coefficient `0.0001` is needed?

FYI: https://github.com/gateio/gateapi-js/blob/master/docs/FuturesOrder.md - size

**Comment by revilwang** [comment]
The value of `size: 1` is determined by `quanto_multiplier` in the [`Contract`](https://github.com/gateio/gateapi-js/blob/master/docs/Contract.md) model. In `BTC_USDT`, it's `0.0001`, which means `0.0001 BTC`.

**Comment by shiqimei** [comment]
Alright, it makes sense to me! Thanks for your explanation :)
