### ISSUE TITLE
Issue with the signature generation with POST request

### ISSUE THREAD

**Issue by capedcrusader23** [gateio/gateapi-js#5]
I have been using POST api of placing order in future using V4 keys.The signature generation algorithm is not working for place order and is giving signature mismatch error.
This is the code for signature i am using for 
Gate.prototype.getSign=function(method,URL,qs,form,ts) 
{
    //var resourcePath = url.slice(url.indexOf('/', url.indexOf('://') + 3));
    var queryString 
    if(method=='GET')
    {
    queryString = unescape(querystring.stringify(qs));
    }
    else if(method=='DELETE')
    {
        queryString=qs
    }
    else
    {
        queryString=''
    }
    console.log("!!!!!!!!!!",typeof(JSON.stringify(form)))
    // FIXME: assume application/json body only
    form = (form !== undefined && form !== null) ?unescape((JSON.stringify(form))) : "";
    console.log(form)
    var hashedPayload = crypto.createHash('sha512').update(form).digest('hex');
    console.log("HASHED PAYLOAD",hashedPayload)
    var signatureString = [method,URL, queryString,hashedPayload,ts].join("\n");
    console.log('signature string to be calculated:'  + signatureString);
    var signature = crypto.createHmac('sha512',unescape(this.apiSecret)).update(unescape(signatureString)).digest('hex');
    console.log("SIGNATURE",signature)
    return signature;
}
Error i am getting
![Screenshot 2020-08-07 at 4 44 22 PM](https://user-images.githubusercontent.com/37747717/89640461-4114d100-d8cd-11ea-8fe4-88516c11380d.png)

Above signing algorithm is working for GET and DELETE request

**Comment by revilwang** [comment]
Sorry for late reply.

Can you please provide an example of the `console.log(form)` output? It seems that you're trying to post form-style body instead of json-style, which leads to `POST` request failure

**Comment by capedcrusader23** [comment]
![Screenshot 2020-08-10 at 8 12 48 PM](https://user-images.githubusercontent.com/37747717/89795323-df12d080-db45-11ea-931e-9788fa91e9a8.png)

**Comment by revilwang** [comment]
how do you pass the form to the server, using application/x-www-form-urlencoded or application/json

**Comment by capedcrusader23** [comment]
using application/json

**Comment by revilwang** [comment]
Make sure the request body content you send to the server is identical to the the content used in signature generation. 

Maybe you can provide a complete snippet from request encapsulation to where the response is consumed.

P.S. better using backtick symbols like below 

~~~
```javascript
# your code snippet here
```
~~~

**Comment by capedcrusader23** [comment]
```
Function to generate request
let body={
                contract:this.symbol,
                size:size,
                price:"0",    
            }
            let header = {'Accept': 'application/json','Content-Type':'application/json'}
            header.KEY = this.apiKey;
            let ts=parseInt((new Date()).getTime()/1000).toString()
            header.SIGN=this.getSign("POST",ORDER,'',body,ts);
            header.Timestamp= ts

            console.log(header)
            let k=await this.Request({method:"POST",url:this.API_QUERY_URL+ORDER,form:body,headers:header})

Function to generate signature 
Gate.prototype.getSign=function(method,URL,qs,form,ts) 
{
    //var resourcePath = url.slice(url.indexOf('/', url.indexOf('://') + 3));
    var queryString 
    if(method=='GET')
    {
    queryString = unescape(querystring.stringify(qs));
    }
    else if(method=='DELETE')
    {
        queryString=qs
    }
    else
    {
        queryString=''
    }
    console.log("!!!!!!!!!!",typeof(JSON.stringify(form)))
    // FIXME: assume application/json body only
    form = (form !== undefined && form !== null) ?unescape((JSON.stringify(form))) : "";
    console.log("THIS IS FORM",form)
    var hashedPayload = crypto.createHash('sha512').update(form).digest('hex');
    console.log("HASHED PAYLOAD",hashedPayload)
    var signatureString = [method,URL, queryString,hashedPayload,ts].join("\n");
    console.log('signature string to be calculated:'  + signatureString);
    var signature = crypto.createHmac('sha512',unescape(this.apiSecret)).update(unescape(signatureString)).digest('hex');
    console.log("SIGNATURE",signature)
    return signature;
}

**Comment by revilwang** [comment]
I'm not sure which HTTP library you are using, but this line:

```javascript
let k=await this.Request({method:"POST",url:this.API_QUERY_URL+ORDER,form:body,headers:header})
```

is quite suspicious. You pass the body using `form:` will may lead your body is formatted using form-style like `contract=xxx&size=xxx&price=xxx`.

**Comment by capedcrusader23** [comment]
This is what Request function looks like
```
Gate.prototype.Request=function(params){
    return new Promise(async(resolve,reject)=>{      
            request(params,function(err,resp,body){
                
                if(err)
                {
                    reject(err)
                }
                else if(body)
                {
                    resolve(body)
                }
                
                
            })
       
    })
}

**Comment by revilwang** [comment]
Which HTTP library are you using?

**Comment by capedcrusader23** [comment]
i am using request module

**Comment by revilwang** [comment]
Then you should change 

```javascript
let k=await this.Request({method:"POST",url:this.API_QUERY_URL+ORDER,form:body,headers:header})
```

to 

```javascript
let k=await this.Request({method:"POST",url:this.API_QUERY_URL+ORDER,body:body,headers:header,json:true})
```

**Comment by capedcrusader23** [comment]
using this 
```
let k=await this.Request({method:"POST",url:this.API_QUERY_URL+ORDER,body:body,headers:header,json:true})
```
didn't solved the problem what i did was this
```
let k=await axios.post(this.API_QUERY_URL+ORDER,body,headers)
```

This solved my issue

**Comment by revilwang** [comment]
You can try the new [NodeJS SDK](https://github.com/gateio/gateapi-nodejs), which is also using `axios`
